# Generated by Django 3.2 on 2023-06-27 19:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amount',
            name='is_actual',
        ),
        migrations.RemoveField(
            model_name='amount',
            name='is_one_time_cost',
        ),
        migrations.CreateModel(
            name='ActualAmount',
            fields=[
                ('actual_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('occurred_on', models.DateField(default=datetime.datetime.now)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actual_amounts', to='budget.amount')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amounts', to='budget.budgetperiod')),
            ],
        ),
    ]
