# Generated by Django 5.2 on 2025-09-03 01:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_add_related_name_for_amounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('goal_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50, 'Name cannot be greater than 50 characters')])),
                ('savings', models.DecimalField(decimal_places=2, max_digits=7)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('expected_contribution', models.DecimalField(decimal_places=2, max_digits=7)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.budget')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
