# Generated by Django 5.2 on 2025-09-04 05:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_add_related_name_for_amounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('goal_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50, 'Name cannot be greater than 50 characters')])),
                ('savings', models.DecimalField(decimal_places=2, max_digits=7)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('expected_contribution', models.DecimalField(decimal_places=2, max_digits=7)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='budget.budget')),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('contribution_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('budget_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.budgetperiod')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.goal')),
            ],
        ),
    ]
